name: Deploy Firebase Functions

on:
  push:
    branches: [
      master,
      email-notifications-cloud-functions # TEMPORARY
    ]
defaults:
  run:
    working-directory: ./src/firebase-functions
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install npm packages
      run: |
        cd functions
        npm install
    - name:  Deploy to Firebase (Production)
      run: ls
      # if: ${{ github.ref == 'refs/heads/master' }}
      uses: w9jds/firebase-action@master
      with:
          args: deploy --only functions -P coindropto
      env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}