name: Deploy Firebase Functions (Development)
env:
  FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
on:
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install npm packages
      run: |
        cd src/firebase/functions
        npm install
        npm run build
    - name:  Test
      uses: w9jds/firebase-action@master
      with:
          args: emulators:exec --project coindropto-dev \"npx jest\"
      env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_PATH: ./src/firebase
    - name:  Deploy
      uses: w9jds/firebase-action@master
      with:
          args: deploy --only functions -P coindropto-dev
      env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_PATH: ./src/firebase